// Code generated by MockGen. DO NOT EDIT.

package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Necromemeser/Cringearium-go/services/courses/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

type MockCourseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCourseRepositoryMockRecorder
}

type MockCourseRepositoryMockRecorder struct {
	mock *MockCourseRepository
}

func NewMockCourseRepository(ctrl *gomock.Controller) *MockCourseRepository {
	mock := &MockCourseRepository{ctrl: ctrl}
	mock.recorder = &MockCourseRepositoryMockRecorder{mock: mock}
	return mock
}

func (m *MockCourseRepository) EXPECT() *MockCourseRepositoryMockRecorder {
	return m.recorder
}

func (m *MockCourseRepository) FindAll(ctx context.Context) ([]*domain.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*domain.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCourseRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCourseRepository)(nil).FindAll), ctx)
}

func (m *MockCourseRepository) FindByID(ctx context.Context, id int64) (*domain.CourseDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.CourseDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCourseRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCourseRepository)(nil).FindByID), ctx, id)
}

func (m *MockCourseRepository) HasAccess(ctx context.Context, userID, courseID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAccess", ctx, userID, courseID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCourseRepositoryMockRecorder) HasAccess(ctx, userID, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAccess", reflect.TypeOf((*MockCourseRepository)(nil).HasAccess), ctx, userID, courseID)
}

func (m *MockCourseRepository) GrantAccess(ctx context.Context, userID, courseID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantAccess", ctx, userID, courseID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCourseRepositoryMockRecorder) GrantAccess(ctx, userID, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantAccess", reflect.TypeOf((*MockCourseRepository)(nil).GrantAccess), ctx, userID, courseID)
}
